export type TrabajosType = {
    id: number;
    nombre_trabajo: string;
    categoria_trabajo: string;
    numero_pagina: number;
    style_trabajo: string;
    complejidad_trabajo: string;
    enlace_trabajo: string;
    enlace_trabajoResumido: string;
    tiempo_trabajo: string;
    resumen_trabajo: string;
    informacion_trabajo: string;
    opinion_trabajo: string;
    valoracion_trabajo: string;
    nombre_archivo: string;
    nombre_imagen: string;
    formato_imagen: string;
    performance_mobile: number;
    accessibility_mobile: number;
    practices_mobile: number;
    seo_mobile: number;
    estado_proyecto: string;
    fecha_finalizacion: string;
    enlace_repositorio: string;
    performance_desktop: number;
    practices_desktop: number;
    accessibility_desktop: number;
    seo_desktop: number;
    rol: string;
    categoria_cliente: string;
    reto_tecnico: string;
    destacado: string | null;
};